version: '3.8'

services:
  mongo:
    image: mongo:6
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5000:5000
    environment:
      - MONGO_URL=mongodb://mongo:27017/pizza-app
    depends_on:
      - mongo
    volumes:
      - ./build:/app/build

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:4444
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  mongo_data:
